# Generated by Django 2.0 on 2019-05-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontoTuristicos',
            new_name='PontoTuristico',
        ),
    ]
