# Generated by Django 2.0 on 2019-05-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('avaliacoes', '0003_auto_20190507_2209'),
        ('comentarios', '0001_initial'),
        ('core', '0009_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontoTuristico',
            new_name='PontosTuristico',
        ),
    ]
